/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CandidateContract } from "./CandidateContract";
export * as factories from "./factories";
export { CandidateContract__factory } from "./factories/CandidateContract__factory";
